### ISSUE TITLE
file conflicts

### ISSUE THREAD

**Issue by ahjolinna** [fabianalexisinostroza/Antu#2]
when I try compile the Antu I get this: 

> error: failed to commit transaction (conflicting files)
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/16/application-x-chm.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/16/application-x-dgn.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/16/application-x-kplato.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/16/application-x-nzb.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/16/libreoffice-master.document.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/16/libreoffice-oasis-master-document.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/16/mail-message-new-list.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/22/application-x-chm.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/22/application-x-dgn.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/22/application-x-kplato.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/22/application-x-nzb.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/22/libreoffice-master.document.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/22/libreoffice-oasis-master-document.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/22/mail-message-new-list.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/32/application-x-chm.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/32/application-x-dgn.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/32/application-x-kplato.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/32/application-x-nzb.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/32/libreoffice-master.document.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/32/libreoffice-oasis-master-document.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/32/mail-message-new-list.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/64/application-x-dgn.svg exists in filesystem
antu-chakra-icon-theme: /usr/share/icons/Antu/mimetypes/64/application-x-kplato.svg exists in filesystem

I also had this problem with antu+1

**Comment by fabianalexisinostroza** [comment]
may be a problem with the mantainer of repository, the theme when is downloaded works fine

**Comment by ahjolinna** [comment]
okay it seems the problem was that when chakra was going to install it... but for some reason it hadn't removed/replaced those files
