### ISSUE TITLE
Error de sintaxis en los nombres de archivos

### ISSUE THREAD

**Issue by Gabrielgtx** [fabianalexisinostroza/Antu#32]
los espacios entre los nombres en estos archivos impide la actualizacion del paquete debido a que el sistema no los elimina correctamente, hay una linea entre la extencion del archivo y el nombre, 
ejemplo:
application-x-chm
.svg

anexo los archivos con este error:
AntuDark/mimetypes/16/:
'application-x-chm' '.svg' 
'application-x-dgn .svg' 
'application-x-kplato .svg' 
'application-x-nzb .svg' 
'libreoffice-master.document .svg' 
'libreoffice-oasis-master-document .svg' 
'mail-message-new-list .svg'

AntuDark/mimetypes/22/:
'application-x-chm .svg' 
'application-x-dgn .svg' 
'application-x-kplato .svg' 
'application-x-nzb .svg' 
'libreoffice-master.document .svg' 
'libreoffice-oasis-master-document .svg' 
'mail-message-new-list .svg'

AntuDark/mimetypes/32/:
'application-x-chm .svg' 
'application-x-dgn .svg' 
'application-x-kplato .svg' 
'application-x-nzb .svg' 
'libreoffice-master.document .svg' 
'libreoffice-oasis-master-document .svg' 
'mail-message-new-list .svg'

AntuDark/mimetypes/64/:
'application-x-dgn .svg' 
'application-x-kplato .svg'

Antu/mimetypes/16/:
'application-x-chm .svg' 
'application-x-dgn .svg' 
'application-x-kplato .svg' 
'application-x-nzb .svg' 
'libreoffice-master.document .svg' 
'libreoffice-oasis-master-document .svg' 
'mail-message-new-list .svg'

Antu/mimetypes/22/:
'application-x-chm .svg'
'application-x-dgn .svg' 
'application-x-kplato .svg' 
'application-x-nzb .svg' 
'libreoffice-master.document .svg' 
'libreoffice-oasis-master-document .svg' 
'mail-message-new-list .svg'

Antu/mimetypes/32/:
'application-x-chm .svg' 
'application-x-dgn .svg' 
'application-x-kplato .svg'
'application-x-nzb .svg' 
'libreoffice-master.document .svg' 
'libreoffice-oasis-master-document .svg' 
'mail-message-new-list .svg'

Antu/mimetypes/64/:
'application-x-dgn .svg' 
'application-x-kplato .svg'

**Comment by SalahAdDin** [comment]
Amigo, has el título más corto y pon todo eso del título en la descripción.

**Comment by fabianalexisinostroza** [comment]
revisando los iconos que manejo para subir al repositorio no están los espacios que mencionas

**Comment by fabianalexisinostroza** [comment]
El problema ya está corregido
