### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by CrisBRM** [fabianalexisinostroza/Antu#33]
Often look like pic related. 

![thumbnails](https://cloud.githubusercontent.com/assets/9098352/13147201/55b45204-d650-11e5-95e1-ec972daf1eba.png)

**Comment by fabianalexisinostroza** [comment]
try reinstall the theme

**Comment by CrisBRM** [comment]
That was after a fresh install. Thumbnail size is 64px.

**Comment by fabianalexisinostroza** [comment]
i don't know about your error, other people don't have it

![screenshot_20160218_135742](https://cloud.githubusercontent.com/assets/14989730/13151160/99e4572a-d647-11e5-92c4-da93120c49f9.png)

**Comment by CrisBRM** [comment]
I don't know what you did, but yesterday's update (as well as today's) fixed it. Pretty cool.

**Comment by fabianalexisinostroza** [comment]
nice (: enjoy
