### ISSUE TITLE
Make it more Gnome compatible

### ISSUE THREAD

**Issue by francoism90** [fabianalexisinostroza/Antu#38]
Although it works fine when using Qt-apps, sometimes the icon theme has issues with GTK-apps:
https://drive.google.com/file/d/0BzfSuVpNNRzqbUhETWI4Wk96Vkk/view?usp=sharing
https://drive.google.com/file/d/0BzfSuVpNNRzqZVYzSjJNYnRZTm8/view?usp=sharing

Are their a few missing symlinks? Or another solution?

Many thanks, also for creating this theme. :)

**Comment by fabianalexisinostroza** [comment]
What desktop environment are you using ??

**Comment by feskyde** [comment]
Bigger icons are caused by a common bug with GTK+ 3 and SVG icons (GTK+ 2 applications doesn't have this problem), for fixing this is necessary to relocate al icons on sized folders (48x48, 32x32, etc.).

**Comment by francoism90** [comment]
@fabianalexisinostroza Using KDE/Plasma (dev) on Arch Linux, should be vanilla as possible. :)

@feskyde Is symlink an option? Don't know how other icon-themes fixing these issues.

Thanks. :)

**Comment by SalahAdDin** [comment]
:+1:

**Comment by CrisBRM** [comment]
Does this mean this icon pack won't work on a DE like, say, Unity? Currently using it on KDE, obviously, but I'm going to give my father an Ubuntu box and it would be nice to know, given how little I know about Unity.

**Comment by fabianalexisinostroza** [comment]
Only plasma 5

**Comment by feskyde** [comment]
@CrisBRM it will work, but you will get a lot of icons from Adwaita (fallback icon theme) because there isn't GNOME support
