### ISSUE TITLE
Could you add some icons for gnome?

### ISSUE THREAD

**Issue by arshavindn** [fabianalexisinostroza/Antu#39]

**Comment by fabianalexisinostroza** [comment]
The icono theme is for plasma not for gnome

**Comment by arshavindn** [comment]
I know, that's why I ask you for a favor.

**Comment by SalahAdDin** [comment]
I think that for now we won't have Antu for gnome for a long time :'(

**Comment by fabianalexisinostroza** [comment]
It is not in plans to redo a theme for gnome, i dont use gnome
