### ISSUE TITLE
Antu+2 icons are broken

### ISSUE THREAD

**Issue by 9Morello** [fabianalexisinostroza/Antu#40]
I downloaded Antu+2 release from here: https://github.com/fabianalexisinostroza/Antu/releases/tag/antu-1.3

But the icons appear like that: http://s27.postimg.org/terbxotsx/antu_bug.png

I'm currently using Antu+1 and the icons display correctly.

**Comment by fabianalexisinostroza** [comment]
may be a problema with your pc, Antu is working fine. Antu is the stock artwork of KaOS and all Works fine

**Comment by 9Morello** [comment]
I'm using Debian Jessie 8.3 with GNOME. Never had this problem with any other icon pack I downloaded on my PC (Vivacious, Paper, Numix-Circles, etc.). I downloaded it more than once to test, extracted it in different HDs.

I'm using Antu+1 right now and the icons display perfectly.

**Comment by fabianalexisinostroza** [comment]
**the icon theme is for Plasma and Works fine on Plasma ... Gnome isn't supported**

**Comment by 9Morello** [comment]
Alright then. Just saying the older version works perfectly on GNOME.

Thanks for the awesome pack!
