### ISSUE TITLE
Caracteres especiales y espacios

### ISSUE THREAD

**Issue by barcia** [fabianalexisinostroza/Antu#43]
Hola Fabián, quería hacerte una pequeña sugerencia.

Instalando el tema Antü desde AUR he detectado que sale un pequeño problema con la **codificación UTF-8** al crear el tar.xz debido a la letra «ü» en el nombre de los Color Schemes.

Aunque el nombre oficial del tema sea Antü, estaría bien que los archivos y directorios del repositorio no llevasen esa «ü» con diéresis (**ni otros caracteres especiales**), ya que pueden surgir errores como este cuando se interactúa con una máquina. De hecho, incluso simplemente los nombres con **espacios o letras mayúsculas** (ej. `Antu Plasma Theme/`) nos dificultan un pelín más la creación de los _scripts_ y son más susceptibles de errores.

Simplemente te lo comento por si quieres valorarlo para versiones futuras.

Un saludo.

**Comment by fabianalexisinostroza** [comment]
voy a pasar todo a antu y no dejaré espacios, pero primero estoy trabajando en el tema plasma
